-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

module(...)

function physicsData(scale)
	local physics = { data =
	{ 
		
		["player_sheet"] = {
			
				{
					density = 2, friction = 20, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -12.6788482666016, 1.88894653320312  ,  2.5802001953125, -43.5845794677734  ,  7.09829711914062, 2.446044921875  ,  8.60527038574219, 75.8499450683594  ,  -11.7707824707031, 77.7831039428711  }
				}  ,
				{
					density = 2, friction = 20, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   2.5802001953125, -43.5845794677734  ,  -12.6788482666016, 1.88894653320312  ,  -20.1997528076172, 3.00314331054688  ,  -10.0131225585938, -44.1918334960938  }
				}  ,
				{
					density = 2, friction = 20, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   7.09829711914062, 2.446044921875  ,  2.5802001953125, -43.5845794677734  ,  13.7835388183594, 2.446044921875  }
				}  
		}
		
	} }

	-- apply scale factor
	local s = scale or 1.0
	for bi,body in pairs(physics.data) do
		for fi,fixture in ipairs(body) do
			for ci,coordinate in ipairs(fixture.shape) do
				fixture.shape[ci] = s * coordinate
			end
		end
	end
	
	function physics:get(name)
		return unpack(self.data[name])
	end
	
	return physics;
end


