-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

module(...)

function physicsData(scale)
	local physics = { data =
	{ 
		
		["player_sheet"] = {
			
				{
					density = 2, friction = 2, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   -8.67884826660156, 0.888946533203125  ,  6.5802001953125, -44.5845794677734  ,  11.0982971191406, 1.446044921875  ,  13.6052703857422, 46.8499450683594  ,  4.97016906738281, 47.4070587158203  ,  -7.77078247070312, 47.7831115722656  }
				}  ,
				{
					density = 2, friction = 2, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   6.5802001953125, -44.5845794677734  ,  -8.67884826660156, 0.888946533203125  ,  -16.1997528076172, 2.00314331054688  ,  -6.01312255859375, -45.1918334960938  }
				}  ,
				{
					density = 2, friction = 2, bounce = 0, 
					filter = { categoryBits = 1, maskBits = 65535 },
					shape = {   11.0982971191406, 1.446044921875  ,  6.5802001953125, -44.5845794677734  ,  17.7835388183594, 1.446044921875  }
				}  
		}
		
	} }

	-- apply scale factor
	local s = scale or 1.0
	for bi,body in pairs(physics.data) do
		for fi,fixture in ipairs(body) do
			for ci,coordinate in ipairs(fixture.shape) do
				fixture.shape[ci] = s * coordinate
			end
		end
	end
	
	function physics:get(name)
		return unpack(self.data[name])
	end
	
	return physics;
end


